sudo: false
language: ruby
cache: bundler
services:
  - docker
before_script:
  - gem install kitchen kitchen-dokken
jobs:
  include:
    - name: "Cookstyle"
      script:
      - bundle exec cookstyle -f fuubar
    - name: "Apt Cookbook"
      script:
      - kitchen test apt-ubuntu-1804
    - name: "Wiki Cookbook"
      script:
      - kitchen test wiki-ubuntu-1804

# safelist
branches:
  only:
  - master
  - migurski/extend-travis
